### ISSUE TITLE
CVerrors

### ISSUE THREAD

**Issue by xdcccr** [MGallow/CVglasso#2]
Hi MGallow,

Thank you for the CVglasso package. 
A question for the following code snippet
`# compute the observed negative validation loglikelihood`
`      # (close enoug)`
`      CV_errors[i, k] = (nrow(X)/2) * (sum(GLASSO$wi * S.valid) - `
 `     determinant(GLASSO$wi,logarithm = TRUE)$modulus[1])`

The form is different from the log-likelihood provided by Friedman et al. (2008) in two ways.

1. It seems that (nrow(X)/2) should be multiplied by ((sum(GLASSO$wi * S.valid) - 
      determinant(GLASSO$wi,logarithm = TRUE)$modulus[1])), rather than be multiplied only by (sum(GLASSO$wi * S.valid).
2. In the example provided by Friedman et al. (2008), they use a log-likelihood added with a penalty term, you can see from formula (1) in the papaer. I am wondering why do you choose the log-likelihood without this term.

The code is cited from this part of your project https://github.com/MGallow/CVglasso/blob/master/R/CV.R 

I am not familiar with github, so if there is misunderstanding of your codes, please let me know.
I would be happy to hear from you.

Best,
Xiaoyue

**Comment by MGallow** [comment]
I believe the code snippet and the formula in (1) are the same.
